site_name: Siddhi-IO-TCP
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
site_favicon: images/favicon.ico
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
pages:
- Welcome to WSO2 Siddhi IO TCP: index.md
- API Docs:
  - 2.0.17: api/2.0.17.md
  - 2.0.16: api/2.0.16.md
  - 2.0.15: api/2.0.15.md
  - 2.0.14: api/2.0.14.md
  - 2.0.13: api/2.0.13.md
  - 2.0.12: api/2.0.12.md
  - 2.0.11: api/2.0.11.md
  - 2.0.10: api/2.0.10.md
  - 2.0.9: api/2.0.9.md
  - 2.0.8: api/2.0.8.md
  - 2.0.7: api/2.0.7.md
  - latest: api/latest.md
- License: license.md
theme: material
