site_name: Siddhi IO TCP
site_description: Siddhi IO TCP Extension
site_author: WSO2
site_url: https://wso2-extensions.github.io/siddhi-io-tcp/
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
repo_name: Siddhi-IO-tcp
repo_url: https://github.com/wso2-extensions/siddhi-io-tcp
copyright: Copyright &copy; 2011 - 2018 WSO2
theme:
  name: material
  logo: images/siddhi-logo-w.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
extra:
  social:
  - type: github
    link: https://github.com/wso2/siddhi
  - type: linkedin
    link: https://www.linkedin.com/groups/13553064
markdown_extensions:
- admonition
- toc(permalink=true)
- codehilite(guess_lang=false)
pages:
- Welcome: index.md
- API Docs:
  - 2.1.2: api/2.1.2.md
  - 2.1.1: api/2.1.1.md
  - 2.1.0: api/2.1.0.md
  - 2.0.20: api/2.0.20.md
  - 2.0.19: api/2.0.19.md
  - 2.0.18: api/2.0.18.md
  - 2.0.17: api/2.0.17.md
  - 2.0.16: api/2.0.16.md
  - 2.0.15: api/2.0.15.md
  - 2.0.14: api/2.0.14.md
  - 2.0.13: api/2.0.13.md
  - 2.0.12: api/2.0.12.md
  - 2.0.11: api/2.0.11.md
  - 2.0.10: api/2.0.10.md
  - 2.0.9: api/2.0.9.md
  - 2.0.8: api/2.0.8.md
  - 2.0.7: api/2.0.7.md
  - latest: api/latest.md
- License: license.md
